[package]
name = "blazy"
description = "A Blender-style UI layer on top of Masonry."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
blazy-canvas.workspace = true

[lints]
workspace = true
